In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from sklearn.metrics import accuracy_score, confusion_matrix, multilabel_confusion_matrix

from sklearn.calibration import CalibratedClassifierCV
from sklearn.dummy import DummyClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.linear_model import Perceptron
from sklearn.linear_model import RidgeClassifier
from sklearn.linear_model import RidgeClassifierCV
from sklearn.linear_model import SGDClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import ExtraTreeClassifier

from warnings import filterwarnings
filterwarnings('ignore')

In [2]:
%%time
df = pd.read_excel('./indeed_results_pp_2020-04-27.xlsx')

Wall time: 46 s


In [3]:
d = df[(df['Title_New'].notnull()) & ((df['Education_Tenth'] == 1) | (df['Education_Twelvth'] == 1) | (df['Education_Bachelors'] == 1) | (df['Education_Masters'] == 1) | (df['Education_Doctorate'] == 1))].reset_index()[['Title_New', 'Education_Tenth', 'Education_Twelvth', 'Education_Bachelors', 'Education_Masters', 'Education_Doctorate']]

In [4]:
d['Title_New'] = d['Title_New'].astype('category')

In [5]:
d['Categorical_Title'] = d['Title_New'].cat.codes

In [6]:
d

Title_New  Education_Tenth  Education_Twelvth  \
0       graphic designer                0                  0   
1       graphic designer                0                  1   
2       graphic designer                0                  0   
3       graphic designer                0                  0   
4       graphic designer                0                  1   
...                  ...              ...                ...   
5335  software developer                0                  0   
5336      data scientist                0                  0   
5337       data engineer                0                  0   
5338      data scientist                0                  0   
5339  back end developer                0                  0   

      Education_Bachelors  Education_Masters  Education_Doctorate  \
0                       1                  0                    0   
1                       1                  0                    0   
2                       1                  0                    0   
3                       1                  0                    0   
4                       1                  0                    0   
...                   ...                ...                  ...   
5335                    1                  0                    0   
5336                    1                  0                    0   
5337                    1                  0                    0   
5338                    1                  0                    0   
5339                    1                  0                    0   

      Categorical_Title  
0                     7  
1                     7  
2                     7  
3                     7  
4                     7  
...                 ...  
5335                 10  
5336                  3  
5337                  2  
5338                  3  
5339                  0  

[5340 rows x 7 columns]

In [7]:
x = d[['Education_Tenth', 'Education_Twelvth', 'Education_Bachelors', 'Education_Masters', 'Education_Doctorate']].values
y = d['Categorical_Title'].values

In [8]:
multilabel_confusion_matrix(y, LogisticRegression().fit(x, y).predict(x))

array([[[5001,    0],
        [ 339,    0]],

       [[5283,    0],
        [  57,    0]],

       [[5099,    0],
        [ 241,    0]],

       [[4928,    0],
        [ 412,    0]],

       [[5339,    0],
        [   1,    0]],

       [[4903,   22],
        [ 404,   11]],

       [[4610,  127],
        [ 560,   43]],

       [[5074,    0],
        [ 266,    0]],

       [[5271,    0],
        [  69,    0]],

       [[4590,   14],
        [ 715,   21]],

       [[ 199, 3611],
        [  39, 1491]],

       [[5129,    0],
        [ 211,    0]],

       [[5278,    0],
        [  62,    0]],

       [[5307,    0],
        [  33,    0]],

       [[5328,    0],
        [  12,    0]],

       [[4987,    0],
        [ 353,    0]]], dtype=int64)

In [9]:
accuracy_score(y, LogisticRegression().fit(x, y).predict(x))

0.2932584269662921

In [10]:
confusion_matrix(y, LogisticRegression().fit(x, y).predict(x))

array([[   0,    0,    0,    0,    0,    0,   13,    0,    0,    0,  326,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   57,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    6,    0,    0,    0,  235,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,   17,    1,    0,    0,    0,  394,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,   11,   22,    0,    0,    0,  382,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,   43,    0,    0,    1,  559,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    2,    4,    0,    0,    0,  260,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   69,
           0,    0,   

In [11]:
accuracy_score(y, CalibratedClassifierCV().fit(x, y).predict(x))

0.2891385767790262

In [12]:
confusion_matrix(y, CalibratedClassifierCV().fit(x, y).predict(x))

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,  339,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   57,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,  241,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,  412,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,  415,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    1,  602,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,  266,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   69,
           0,    0,   

In [13]:
accuracy_score(y, DummyClassifier().fit(x, y).predict(x))

0.14250936329588015

In [14]:
confusion_matrix(y, DummyClassifier().fit(x, y).predict(x))

array([[ 28,   0,  21,  20,   0,  30,  37,  11,   7,  44,  85,  14,   3,
          7,   2,  30],
       [  3,   1,   1,   3,   0,   2,   5,   5,   2,   9,  18,   2,   3,
          0,   1,   2],
       [ 13,   1,   5,  20,   0,  12,  29,  15,   4,  36,  72,  15,   1,
          1,   1,  16],
       [ 20,   6,  17,  29,   0,  31,  65,  20,   3,  37, 123,  25,   5,
          2,   2,  27],
       [  0,   0,   0,   0,   0,   1,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [ 31,   2,  20,  33,   0,  33,  40,  20,   4,  52, 131,  19,   4,
          0,   0,  26],
       [ 43,   5,  32,  42,   0,  48,  76,  28,   3,  84, 159,  23,   2,
          2,   5,  51],
       [ 13,   2,  15,  14,   0,  30,  38,   9,   5,  24,  79,  15,   2,
          2,   1,  17],
       [ 10,   1,   1,   7,   0,   5,  12,   2,   0,  14,   7,   3,   1,
          1,   0,   5],
       [ 42,  12,  41,  57,   0,  50,  75,  41,   7, 106, 201,  36,   5,
          4,   1,  58],
       [ 99,  19,  79, 131,   

In [15]:
accuracy_score(y, AdaBoostClassifier().fit(x, y).predict(x))

0.19831460674157303

In [16]:
confusion_matrix(y, AdaBoostClassifier().fit(x, y).predict(x))

array([[  2,   0,   0,   0,   0,   0,  34,   0,   0,   0, 292,   0,   0,
         11,   0,   0],
       [  0,   0,   0,   0,   0,   0,  14,   0,   0,   0,  43,   0,   0,
          0,   0,   0],
       [  2,   0,   0,   0,   0,   0,  36,   0,   0,   0, 199,   0,   0,
          4,   0,   0],
       [  6,   0,   0,   0,   0,   0,  53,   0,   0,   0, 340,   0,   0,
         13,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,
          0,   0,   0],
       [  1,   0,   0,   0,   0,   0,  82,   0,   0,   0, 323,   0,   0,
          9,   0,   0],
       [  1,   0,   0,   0,   0,   0, 123,   0,   0,   0, 408,   0,   1,
         70,   0,   0],
       [  0,   0,   0,   0,   0,   0,  26,   0,   0,   0, 214,   0,   0,
         26,   0,   0],
       [  0,   0,   0,   0,   0,   0,  27,   0,   0,   0,  42,   0,   0,
          0,   0,   0],
       [ 22,   0,   0,   0,   0,   0, 244,   0,   0,   0, 430,   0,  21,
         19,   0,   0],
       [ 23,   0,   0,   0,   

In [17]:
accuracy_score(y, BaggingClassifier().fit(x, y).predict(x))

0.2955056179775281

In [18]:
confusion_matrix(y, BaggingClassifier().fit(x, y).predict(x))

array([[   2,    0,    0,    0,    0,    0,   13,    0,    0,    0,  324,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   57,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    6,    0,    0,    2,  233,
           0,    0,    0,    0,    0],
       [   2,    0,    0,   17,    0,    0,    1,    0,    0,    4,  388,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
           0,    0,    0,    0,    0],
       [   0,    0,    0,   11,    0,    0,   22,    0,    0,    1,  381,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,   43,    0,    0,    2,  558,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    2,    0,    0,    4,    0,    0,    0,  260,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   69,
           0,    0,   

In [19]:
accuracy_score(y, ExtraTreesClassifier().fit(x, y).predict(x))

0.2955056179775281

In [20]:
confusion_matrix(y, ExtraTreesClassifier().fit(x, y).predict(x))

array([[   2,    0,    0,    0,    0,    0,   13,    0,    0,    0,  324,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   57,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    6,    0,    0,    0,  235,
           0,    0,    0,    0,    0],
       [   2,    0,    0,   17,    0,    0,    1,    0,    0,    0,  392,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
           0,    0,    0,    0,    0],
       [   0,    0,    0,   11,    0,    0,   22,    0,    0,    0,  382,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,   43,    0,    0,    1,  559,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    2,    0,    0,    4,    0,    0,    0,  260,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   69,
           0,    0,   

In [21]:
accuracy_score(y, GradientBoostingClassifier().fit(x, y).predict(x))

0.2955056179775281

In [22]:
confusion_matrix(y, GradientBoostingClassifier().fit(x, y).predict(x))

array([[   0,    0,    0,    2,    0,    0,   13,    0,    0,    0,  324,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   57,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    6,    0,    0,    0,  235,
           0,    0,    0,    0,    0],
       [   0,    0,    0,   19,    0,    0,    1,    0,    0,    0,  392,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
           0,    0,    0,    0,    0],
       [   0,    0,    0,   11,    0,    0,   22,    0,    0,    0,  382,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,   43,    0,    0,    1,  559,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    2,    0,    0,    4,    0,    0,    0,  260,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   69,
           0,    0,   

In [23]:
accuracy_score(y, RandomForestClassifier().fit(x, y).predict(x))

0.2955056179775281

In [24]:
confusion_matrix(y, RandomForestClassifier().fit(x, y).predict(x))

array([[   2,    0,    0,    0,    0,    0,   13,    0,    0,    0,  324,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   57,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    6,    0,    0,    0,  235,
           0,    0,    0,    0,    0],
       [   2,    0,    0,   17,    0,    0,    1,    0,    0,    0,  392,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
           0,    0,    0,    0,    0],
       [   0,    0,    0,   11,    0,    0,   22,    0,    0,    0,  382,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,   43,    0,    0,    1,  559,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    2,    0,    0,    4,    0,    0,    0,  260,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   69,
           0,    0,   

In [25]:
accuracy_score(y, GaussianProcessClassifier().fit(x, y).predict(x))

0.2951310861423221

In [26]:
confusion_matrix(y, GaussianProcessClassifier().fit(x, y).predict(x))

array([[   0,    0,    0,    0,    0,    0,   13,    0,    0,    0,  326,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   57,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    6,    0,    0,    0,  235,
           0,    0,    0,    0,    0],
       [   0,    0,    0,   17,    0,    0,    1,    0,    0,    0,  394,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
           0,    0,    0,    0,    0],
       [   0,    0,    0,   11,    0,    0,   22,    0,    0,    0,  382,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,   43,    0,    0,    1,  559,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    2,    0,    0,    4,    0,    0,    0,  260,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   69,
           0,    0,   

In [27]:
accuracy_score(y, PassiveAggressiveClassifier().fit(x, y).predict(x))

0.16292134831460675

In [28]:
confusion_matrix(y, PassiveAggressiveClassifier().fit(x, y).predict(x))

array([[   0,    0,    0,    0,    0,    0,  332,    0,    0,    0,    5,
           0,    0,    2,    0,    0],
       [   0,    0,    0,    0,    0,    0,   57,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,  239,    0,    0,    0,    2,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,  374,    0,    0,    0,   36,
           0,    0,    2,    0,    0],
       [   0,    0,    0,    0,    0,    0,    1,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,  407,    0,    0,    0,    8,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,  594,    0,    0,    0,    9,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,  258,    0,    0,    0,    8,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,   69,    0,    0,    0,    0,
           0,    0,   

In [29]:
accuracy_score(y, Perceptron().fit(x, y).predict(x))

0.28389513108614234

In [30]:
confusion_matrix(y, Perceptron().fit(x, y).predict(x))

array([[   0,    0,    0,    0,    0,    0,   13,    0,    0,    0,  326,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   57,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    2,    0,    6,    0,    0,    0,  233,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    4,    0,   18,    0,    0,    0,  390,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    1,    0,   33,    0,    0,    0,  381,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    1,    0,   44,    0,    0,    0,  558,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    6,    0,    0,    0,  260,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   69,
           0,    0,   

In [31]:
accuracy_score(y, RidgeClassifier().fit(x, y).predict(x))

0.29213483146067415

In [32]:
confusion_matrix(y, RidgeClassifier().fit(x, y).predict(x))

array([[   0,    0,    0,    0,    0,    0,   13,    0,    0,    0,  326,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   57,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    6,    0,    0,    0,  235,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    1,    0,    0,    0,  411,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,   22,    0,    0,    0,  393,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,   43,    0,    0,    1,  559,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    4,    0,    0,    0,  262,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   69,
           0,    0,   

In [33]:
accuracy_score(y, RidgeClassifierCV().fit(x, y).predict(x))

0.29213483146067415

In [34]:
confusion_matrix(y, RidgeClassifierCV().fit(x, y).predict(x))

array([[   0,    0,    0,    0,    0,    0,   13,    0,    0,    0,  326,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   57,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    6,    0,    0,    0,  235,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    1,    0,    0,    0,  411,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,   22,    0,    0,    0,  393,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,   43,    0,    0,    1,  559,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    4,    0,    0,    0,  262,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   69,
           0,    0,   

In [35]:
accuracy_score(y, SGDClassifier().fit(x, y).predict(x))

0.19307116104868913

In [36]:
confusion_matrix(y, SGDClassifier().fit(x, y).predict(x))

array([[  0,   0,   0, 306,   0,   0,   0,   0,   0,   0,  33,   0,   0,
          0,   0,   0],
       [  0,   0,   0,  43,   0,   0,   0,   0,   0,   0,  14,   0,   0,
          0,   0,   0],
       [  0,   0,   0, 205,   0,   0,   0,   0,   0,   2,  34,   0,   0,
          0,   0,   0],
       [  0,   0,   0, 304,   0,   0,   0,   0,   0,   4, 104,   0,   0,
          0,   0,   0],
       [  0,   0,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [  0,   0,   0, 317,   0,   0,   0,   0,   0,   1,  97,   0,   0,
          0,   0,   0],
       [  0,   0,   0, 443,   0,   0,   0,   0,   0,   2, 158,   0,   0,
          0,   0,   0],
       [  0,   0,   0, 207,   0,   0,   0,   0,   0,   0,  59,   0,   0,
          0,   0,   0],
       [  0,   0,   0,  42,   0,   0,   0,   0,   0,   0,  27,   0,   0,
          0,   0,   0],
       [  0,   0,   0, 409,   0,   0,   0,   0,   0,  41, 286,   0,   0,
          0,   0,   0],
       [  0,   0,   0, 862,   

In [37]:
accuracy_score(y, KNeighborsClassifier().fit(x, y).predict(x))

0.15393258426966291

In [38]:
confusion_matrix(y, KNeighborsClassifier().fit(x, y).predict(x))

array([[285,   0,   0,   0,   0,  21,   0,  13,   0,   0,  20,   0,   0,
          0,   0,   0],
       [ 43,   0,   0,   0,   0,  14,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [187,   0,   0,   0,   0,  30,   0,   6,   0,   2,  16,   0,   0,
          0,   0,   0],
       [267,   0,   0,  17,   0,  52,   0,   1,   0,   4,  71,   0,   0,
          0,   0,   0],
       [  1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [266,   0,   0,  11,   0,  60,   0,  22,   0,   1,  55,   0,   0,
          0,   0,   0],
       [379,   0,   0,   0,   0,  80,   0,  43,   0,   2,  99,   0,   0,
          0,   0,   0],
       [199,   0,   0,   2,   0,  22,   0,   4,   0,   0,  39,   0,   0,
          0,   0,   0],
       [ 42,   0,   0,   0,   0,  27,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [390,   0,   0,   0,   0, 228,   0,  16,   0,  41,  61,   0,   0,
          0,   0,   0],
       [738,   0,   0,   3,   

In [39]:
accuracy_score(y, MLPClassifier().fit(x, y).predict(x))

0.2955056179775281

In [40]:
confusion_matrix(y, MLPClassifier().fit(x, y).predict(x))

array([[   0,    0,    0,    0,    0,    0,   13,    0,    0,    0,  326,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   57,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    6,    0,    0,    0,  235,
           0,    0,    0,    0,    0],
       [   0,    0,    0,   17,    0,    0,    1,    0,    0,    0,  394,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
           0,    0,    0,    0,    0],
       [   0,    0,    0,   11,    0,    0,   22,    0,    0,    0,  382,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,   43,    0,    0,    1,  559,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    2,    0,    0,    4,    0,    0,    0,  260,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   69,
           0,    0,   

In [41]:
accuracy_score(y, LinearSVC().fit(x, y).predict(x))

0.29213483146067415

In [42]:
confusion_matrix(y, LinearSVC().fit(x, y).predict(x))

array([[   0,    0,    0,    0,    0,    0,   13,    0,    0,    0,  326,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   57,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    6,    0,    0,    0,  235,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    1,    0,    0,    0,  411,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,   22,    0,    0,    0,  393,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,   43,    0,    0,    1,  559,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    4,    0,    0,    0,  262,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   69,
           0,    0,   

In [43]:
accuracy_score(y, SVC().fit(x, y).predict(x))

0.2955056179775281

In [44]:
confusion_matrix(y, SVC().fit(x, y).predict(x))

array([[   2,    0,    0,    0,    0,    0,   13,    0,    0,    0,  324,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   57,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    6,    0,    0,    0,  235,
           0,    0,    0,    0,    0],
       [   2,    0,    0,   17,    0,    0,    1,    0,    0,    0,  392,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
           0,    0,    0,    0,    0],
       [   0,    0,    0,   11,    0,    0,   22,    0,    0,    0,  382,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,   43,    0,    0,    1,  559,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    2,    0,    0,    4,    0,    0,    0,  260,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   69,
           0,    0,   

In [45]:
accuracy_score(y, DecisionTreeClassifier().fit(x, y).predict(x))

0.2955056179775281

In [46]:
confusion_matrix(y, DecisionTreeClassifier().fit(x, y).predict(x))

array([[   2,    0,    0,    0,    0,    0,   13,    0,    0,    0,  324,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   57,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    6,    0,    0,    0,  235,
           0,    0,    0,    0,    0],
       [   2,    0,    0,   17,    0,    0,    1,    0,    0,    0,  392,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
           0,    0,    0,    0,    0],
       [   0,    0,    0,   11,    0,    0,   22,    0,    0,    0,  382,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,   43,    0,    0,    1,  559,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    2,    0,    0,    4,    0,    0,    0,  260,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   69,
           0,    0,   

In [47]:
accuracy_score(y, ExtraTreeClassifier().fit(x, y).predict(x))

0.2955056179775281

In [48]:
confusion_matrix(y, ExtraTreeClassifier().fit(x, y).predict(x))

array([[   2,    0,    0,    0,    0,    0,   13,    0,    0,    0,  324,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   57,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    6,    0,    0,    0,  235,
           0,    0,    0,    0,    0],
       [   2,    0,    0,   17,    0,    0,    1,    0,    0,    0,  392,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
           0,    0,    0,    0,    0],
       [   0,    0,    0,   11,    0,    0,   22,    0,    0,    0,  382,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,   43,    0,    0,    1,  559,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    2,    0,    0,    4,    0,    0,    0,  260,
           0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   69,
           0,    0,   